#=== Varianta pro pouziti PostgresSQL databaze v pc ===
spring.application.name=ragnarok_customers_training_diary
server.port = 8080

# Thymeleaf engine configuration
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Configuration PostgreSQL db
spring.datasource.url=jdbc:postgresql://localhost:5432/ragnarok_diary_database
spring.datasource.username=postgres
spring.datasource.password=Meto1990
# spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

# Logging SQL + binding parameters
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

# Date and time configuration
spring.jackson.date-format=dd.MM.yyyy
spring.jackson.time-zone=UTC

# ENUM case-insensitivity
spring.jackson.mapper.accept-case-insensitive-enums=true

#metriky kv?li cache
management.endpoints.web.exposure.include=health,metrics,caches,heapdump,threaddump
management.endpoint.metrics.enabled=true

# Maximální po?et obslu?ných vláken
server.tomcat.threads.max=50

# Po?et po?adavk? ?ekajících ve front?, kdy? jsou vlákna obsazená
server.tomcat.accept-count=50

#debug cache
logging.level.org.springframework.cache=DEBUG


## === PostgreSQL on Railway ===
#spring.datasource.url=jdbc:postgresql://postgres-copy.railway.internal:5432/railway
#spring.datasource.username=postgres
#spring.datasource.password=DkEmbcshcNBpGckWgljbnqyrAYIEwDHx
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#server.forward-headers-strategy=framework
#
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
## Logging SQL + binding parameters
#logging.level.org.hibernate.SQL=INFO
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
#
## Date and time configuration
#spring.jackson.date-format=dd.MM.yyyy
#spring.jackson.time-zone=UTC
#
## ENUM case-insensitivity
#spring.jackson.mapper.accept-case-insensitive-enums=true
#
##metriky kvuli cache
#management.endpoints.web.exposure.include=health,metrics,caches,heapdump,threaddump
#management.endpoint.metrics.enabled=true
#
##maximum request lines
#server.tomcat.threads.max=50
##"stand by" requests
#server.tomcat.accept-count=50
#
##hikari
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.leak-detection-threshold=20000
#
##debug cache
#logging.level.org.springframework.cache=DEBUG