-- Phase 12 / A3: per-round skutečný záznam circuitu.
-- Pro každé kolo × krok lze zapsat, co se reálně odehrálo (vyřazení/náhrada/jiné reps/váha).
-- Logování probíhá na detailu tréninku po odcvičení (ne v create formu).

CREATE TABLE circuit_round_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    circuit_config_id BIGINT  NOT NULL REFERENCES circuit_config(training_exercise_id) ON DELETE CASCADE,
    round_index       INTEGER NOT NULL,   -- 1-based pořadí kola
    step_order        INTEGER NOT NULL,   -- = circuit_step.order_index (0-based)
    skipped           BOOLEAN NOT NULL DEFAULT FALSE,
    substitute_name   VARCHAR(128),       -- náhradní cvik pro toto kolo (NULL = dle plánu)
    actual_reps       INTEGER,
    actual_weight_kg  NUMERIC(7,2),
    note              VARCHAR(255)
);

CREATE INDEX idx_circuit_round_entry_config ON circuit_round_entry(circuit_config_id);
