-- Phase 20a/b (ScoutMeto): rozšiřitelný číselník pro pohybový vzorec a náčiní v katalogu.
-- Systémové hodnoty (z původních enumů) zůstávají, admin přidá vlastní; vlastní lze smazat.
-- Entity ExerciseCatalogItem.movementPattern/equipment přechází z enumu na String (sloupec
-- už byl VARCHAR, takže bez změny sloupce).

CREATE TABLE catalog_attribute_option (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind      VARCHAR(32)  NOT NULL,   -- MOVEMENT_PATTERN | EQUIPMENT
    name      VARCHAR(64)  NOT NULL,
    is_system BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_catalog_attr_option UNIQUE (kind, name)
);

CREATE INDEX idx_catalog_attr_option_kind ON catalog_attribute_option(kind);

-- Seed: pohybové vzorce (system)
INSERT INTO catalog_attribute_option (kind, name, is_system) VALUES
    ('MOVEMENT_PATTERN', 'PUSH', TRUE),
    ('MOVEMENT_PATTERN', 'PULL', TRUE),
    ('MOVEMENT_PATTERN', 'SQUAT', TRUE),
    ('MOVEMENT_PATTERN', 'HINGE', TRUE),
    ('MOVEMENT_PATTERN', 'LUNGE', TRUE),
    ('MOVEMENT_PATTERN', 'ROTATION', TRUE),
    ('MOVEMENT_PATTERN', 'CARRY', TRUE),
    ('MOVEMENT_PATTERN', 'GAIT', TRUE),
    ('MOVEMENT_PATTERN', 'ISOMETRIC', TRUE),
    ('MOVEMENT_PATTERN', 'PLYO', TRUE),
    ('MOVEMENT_PATTERN', 'OTHER', TRUE);

-- Seed: náčiní (system)
INSERT INTO catalog_attribute_option (kind, name, is_system) VALUES
    ('EQUIPMENT', 'BARBELL', TRUE),
    ('EQUIPMENT', 'KETTLEBELL', TRUE),
    ('EQUIPMENT', 'DUMBBELL', TRUE),
    ('EQUIPMENT', 'BODYWEIGHT', TRUE),
    ('EQUIPMENT', 'BAND', TRUE),
    ('EQUIPMENT', 'MACHINE', TRUE),
    ('EQUIPMENT', 'CABLE', TRUE),
    ('EQUIPMENT', 'NONE', TRUE),
    ('EQUIPMENT', 'OTHER', TRUE);
