-- Phase 21 (ScoutMeto): textová šablona plánu (prostý text, dlouhodobý plán).
-- Admin vytvoří šablonu (template=TRUE, originál zůstává u trenéra), přiřadí uživateli →
-- vznikne editovatelná KOPIE (template=FALSE, owner=user). User si kopii čte i edituje.

CREATE TABLE text_plan (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(128) NOT NULL,
    body               TEXT         NOT NULL,
    is_template        BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id           BIGINT       REFERENCES account(id),          -- kopie: vlastník; šablona: NULL
    created_by_id      BIGINT       REFERENCES account(id),          -- admin autor
    source_template_id BIGINT       REFERENCES text_plan(id),        -- kopie: odkaz na šablonu
    created_at         TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_text_plan_owner ON text_plan(owner_id) WHERE is_template = FALSE;
CREATE INDEX idx_text_plan_template ON text_plan(is_template);
